project:
  type: website

website:
  title: "신록예찬's Blog"
  
  page-footer:
    border: true
  
  navbar:
    left:
      - text: DL2022
        href: https://guebin.github.io/DL2022/
      - text: AP2023
        href: https://guebin.github.io/AP2023/
      - text: PP2023
        href: https://guebin.github.io/PP2023/    
      - text: DV2022
        href: https://guebin.github.io/DV2022/
      - text: SC2022
        href: https://guebin.github.io/SC2022/
      - text: DS2022
        href: https://guebin.github.io/DS2022/
      - text: SP2023
        href: https://guebin.github.io/SP2023/
      - text: IR2021
        href: https://guebin.github.io/IR2021/
      - text: yechan
        href: https://miruetoto.github.io/yechan/
      - text: yechan2
        href: https://miruetoto.github.io/yechan2/
    right: 
      - icon: github
        href: https://github.com/miruetoto/yechan3
  sidebar:
    style: "docked"
    search: true
    contents:
      - 0_notes.qmd
      - 1_essays.qmd
      - section: "**Studies**"
        contents:
          - 2_cgsp.qmd    
          - 2_pyg.qmd
          - 2_reviews.qmd    
      - section: "**Researches**"
        contents:
          - 3_yechan.qmd
          - 3_yeon.qmd
          - 3_boram.qmd
          - 3_pinkocto.qmd
      - temp.qmd      

format:
  html:
    theme: cosmo
    css: styles.css