project:
  type: website

website:
  title: "yechan3"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/miruetoto/yechan3
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false
    code-line-numbers: true
    code-copy: true
    
