project:
  type: website

website:
  title: "신록예찬's Blog"
  
  page-footer:
    border: true
  
  navbar:
    left:
      - text: DL2022
        href: https://guebin.github.io/DL2022/
      - text: DV2022
        href: https://guebin.github.io/DV2022/
      - text: IP2022
        href: https://guebin.github.io/IP2022/
      - text: SC2022
        href: https://guebin.github.io/SC2022/
      - text: DS2022
        href: https://guebin.github.io/DS2022/
      - text: IR2021
        href: https://guebin.github.io/IR2021/
      - text: yechan(old)
        href: https://miruetoto.github.io/yechan/
      - text: yechan2
        href: https://miruetoto.github.io/yechan2/


    right: 
      - text: git-repo
        href: https://github.com/miruetoto/yechan3

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Codes"
        contents:
          - 1_codes_pl.qmd
      - section: "Let's Study"
        contents:
          - 2_study_cgsp.qmd
          - 2_study_essays.qmd
      - section: "Researches"
        contents:
          - 3_researches_hst.qmd
          - 3_researches_stgcn.qmd
      - 4_reviews.qmd
      - 5_notes.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: false
    code-line-numbers: true
    code-copy: true
    
